// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
module.exports = {
  // 'primary-color': '#10e99b',
  'card-actions-background': '#f5f8fa',
  '@primary-color': '#108ee9',
  '@link-color': '#108ee9',
  '@border-radius-base': '2px',
  '@font-size-base': '12px',
  '@line-height-base': '1.2',
  '@border-radius-sm': '2px',
  '@shadow-color': 'rgba(0,0,0,0.05)',
  '@shadow-1-down': '4px 4px 40px @shadow-color',
  '@border-color-split': '#f4f4f4',
  '@border-color-base': '#e5e5e5',
  '@menu-dark-bg': '#00152a',
  '@text-color': '#666',
  '@dark-half': '#494949',
  '@purple': '#d897eb',
  '@shadow-1': '4px 4px 20px 0 rgba(0,0,0,0.01)',
  '@shadow-2': '4px 4px 40px 0 rgba(0,0,0,0.05)',
  '@transition-ease-in': 'all 0.3s ease-out',
  '@transition-ease-out': 'all 0.3s ease-out',
  '@ease-in': 'ease-in',
  '@menu-item-height': '30px', // 菜单高度 height, line-height
  '@card-padding-base': '6px',
  '@card-padding-wider': '8px',
  '@menu-collapsed-width': '60px',
  '@card-head-height': '30px',
  '@form-item-margin-bottom': '4px',
  '@menu-inline-toplevel-item-height': '28px',
  '@zindex-message': '5000',
  '@zindex-modal': '1000',
  '@zindex-popover': '1000',
  '@zindex-pickser': '1000',
}
